MODEL:
  BACKBONE:
    NAME: "build_resnest_fpn_backbone"
  META_ARCHITECTURE: "PanopticFCN"
  WEIGHTS: "https://s3.us-west-1.wasabisys.com/resnest/detectron/resnest101_detectron-486f69a8.pth"
  MASK_ON: True
  PIXEL_MEAN: [123.68, 116.779, 103.939]
  PIXEL_STD: [58.393, 57.12, 57.375]
  RESNETS:
    DEPTH: 101
    STRIDE_IN_1X1: False
    RADIX: 2
    NORM: "SyncBN"
    OUT_FEATURES: ["res2", "res3", "res4", "res5"]
  FPN:
    NORM: "SyncBN"
    IN_FEATURES: ["res2", "res3", "res4", "res5"]
  FEATURE_ENCODER:
    DEFORM: True
    CONVS_DIM: 256
DATASETS:
  TRAIN: ("coco_2017_train_panoptic_separated",)
  TEST: ("coco_2017_val_panoptic_separated",)
DATALOADER:
  FILTER_EMPTY_ANNOTATIONS: True
SOLVER:
  BASE_LR: 0.01
  WEIGHT_DECAY: 1e-4
  LR_SCHEDULER_NAME: "WarmupPolyLR"
  POLY_LR_POWER: 0.9
  WARMUP_ITERS: 1000
  WARMUP_FACTOR: 0.001
  WARMUP_METHOD: "linear"
  CLIP_GRADIENTS:
    ENABLED: True
    CLIP_VALUE: 35.0
  IMS_PER_BATCH: 16
  MAX_ITER: 270000
  CHECKPOINT_PERIOD: 10000
INPUT:
  MIN_SIZE_TRAIN: (640, 672, 704, 736, 768, 800)
  MIN_SIZE_TRAIN_SAMPLING: "choice"
  MIN_SIZE_TEST: 800
  MAX_SIZE_TRAIN: 1333
  MAX_SIZE_TEST: 1333
  MASK_FORMAT: "bitmask"
  FORMAT: "RGB"
TEST:
  PRECISE_BN:
    ENABLED: True
VERSION: 2

